[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ocr-ops",
    "pandas",
    "pokemontcgsdk",
    "bidict",
    "ordered_set",
    "requests",
    "Pillow==9.5.0"
]
build-backend = "setuptools.build_meta"