[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "ocr-ops",
    "pandas",
    "pokemontcgsdk",
    "bidict",
    "ordered_set",
    "requests"
]
build-backend = "setuptools.build_meta"